### ISSUE TITLE
Allow vertical layout

### ISSUE THREAD

**Issue by lbeltrame** [akrutzler/plasma-audio-device-switcher#2]
Some translations have very long names for ports, and this makes the plasmoid very long, even more so if there are outputs added on the fly.

Ideally there should be the possibility, in this case, for a vertical layout rather than a horizontal one.

**Comment by akrutzler** [comment]
Shouldn't be too hard to implement :+1: 
You can also try the 'Show icons only' mode introduced with 0.1.0. This makes the widget much smaller.
